title: "selfdriven Nexus"
description: ""
baseurl: ""
url: ""
context: "nexus"
repo: "selfdriven-services/selfdriven-nexus"

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: selfdriven

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - _well-known/